### ISSUE TITLE
Flow.setHistory() equivalent 

### ISSUE THREAD

**Issue by alexrwegener** [lukaspili/Mortar-architect#1]
It looks like Dispatcher always executes StackablePaths sequentially. Is there any way to create a stack of StackablePaths and only animate to the top of the stack? For instance instead of animating MyPopupView -> HomeView -> SubnavView -> SlidesView animate MyPopupView -> SlidesView with the same StackablePath history.

**Comment by lukaspili** [comment]
Yes I removed during last core refactoring and didn't add it back yet. Will do today.

**Comment by alexrwegener** [comment]
:+1:

**Comment by lukaspili** [comment]
Fixed in 0.14-SNAPSHOT.
There is no more intermediate view transitions.
It has impact on `Navigator.chain()`, `Navigator.replace()` and the new `Navigator.set()`.

**Comment by alexrwegener** [comment]
Nice! I'll take a look this weekend.
