### ISSUE TITLE
Sample app as library

### ISSUE THREAD

**Issue by jjvargas** [lukaspili/Mortar-architect#18]
In my project I am trying to use a white label app as a library.  I made a small simulation of a simple android app and by changing the build.gradle to apply plugin: 'com.android.library and in the sample app works but my  in my app that uses Mortar Architect is no working.

It looks like it cannot find the classes that are auto-generated. 

Any idea how to fix this?

\Mortar-architect\app\src\main\java\com\mortarnav\presenter\HomePresenter.java:69: error: cannot find symbol   Navigator.get(getView()).push(new SubnavStackable());

**Comment by jjvargas** [comment]
I found the problem,

This is related to using ButterKnife in a library project, these were the source of the problem and not being able to generate the Stackable classes. I ended up using ButterFork and its working now :)

**Comment by lukaspili** [comment]
Thanks for the heads up, didn't know about the butterfork project :+1:
