### ISSUE TITLE
Does this library support all the fragments-related classes, like ViewPager?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [lukaspili/Mortar-architect#2]
as the title says.

**Comment by lukaspili** [comment]
Yes. There is one example of ViewPager in the example project (see SlidesPresenter and SlidePagePresenter.) 
And also **architect-commons** provides a PagerAdapter: https://github.com/lukaspili/Mortar-architect/blob/master/commons/src/main/java/architect/commons/adapter/StackablePagerAdapter.java

**Comment by AndroidDeveloperLB** [comment]
Nice. Thank you.
