### ISSUE TITLE
Remove unnecessary view groups from sample app

### ISSUE THREAD

**Issue by alexrwegener** [lukaspili/Mortar-architect#4]
At the moment the sample app inflates an unnecessary view group when inflating a view class. The easy fix would be to replace the root view group defined in xml with a merge element.

I think a cleaner approach would be to reference the view itself in xml. I'm still wrapping my head around architect so I don't necessarily know the implications of what I'm about to suggest so bear with me :). Instead of inflating a layout file in the constructor of the view push the inflation to the StackablePath implementation.

So the HomeView / HomeStackable / home_view.xml would look like

``` java
public HomeView(Context context, AttributeSet attributeSet) {
  super(context, attributeSet);
  DaggerService.<HomeStackable.Component>get(context).inject(this);
}

@Override protected void onFinishInflate() {
  ButterKnife.bind(this);
}
```

and 

``` java
@Override public View createView(Context context, ViewGroup parent) {
  return View.inflate(context, R.layout.home_view, parent);
}
```

and

``` xml
<?xml version="1.0" encoding="utf-8"?>
<com.mortarnav.view.HomeView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
...
```

This would require a signature change on StackablePath, internal record keeping of the parent ViewGroup, and a way to specify a layout file for a view within robot. What do you think?

**Comment by lukaspili** [comment]
You are right. I personally prefer using the View class with <merge> on the xml, because I can then better reuse them in other xml files (without having to use <layout> which adds an useless viewgroup).

But it should be up to the developer to choose the way he prefers.
I will update `StackablePath createView()` method to the following:

``` java
public interface StackablePath extends Stackable {
   View createView(Context context, ViewGroup parent);
}
```

You will then be able to return view by inflating a layout:

``` java
public class HomeStackable implements StackablePath {
    @Override
    public View createView(Context context, ViewGroup parent) {
        return LayoutInflater.from(context).inflate(R.layout.home_view, parent, false);
    }
}
```

**Comment by alexrwegener** [comment]
The StackablePath change sounds good. :+1: 
Will there be an optional option to provide a layout file via annotation? Also let me know if you need / want help on anything. I'm more than willing. :)

**Comment by lukaspili** [comment]
By annotation, do you mean `@AutoStackable`? 
I'm planning to implement the following:

``` java
@AutoStackable(
        component = @AutoComponent(includes = StandardAutoComponent.class),
        pathWithLayout = R.layout.slides_view
)
@DaggerScope(SlidesPresenter.class)
public class SlidesPresenter extends ViewPresenter<SlidesView> {
}
```

Thanks for the help offering. You are actually already helping :)

**Comment by alexrwegener** [comment]
I do! And that looks good. :+1:

**Comment by lukaspili** [comment]
Done in 0.14-SNAPSHOT.

**Comment by alexrwegener** [comment]
I'll check this out as well. Thanks!
